"""Initial Migration

Revision ID: 45969ab4e805
Revises: 
Create Date: 2022-08-26 19:28:49.655696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45969ab4e805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
